### ISSUE TITLE
About how contracts automatically deal with buy back and burn.

### ISSUE THREAD

**Issue by matthewalan0** [OlympusDAO/olympus-contracts#31]
GM, I have some questions with 👇:
```
When OHM trades below 1 DAI, 
how the contract buy back and burn OHM? 
And could I know the exact code lines that written in the contract. 
Could I know exactly how this mechanism works(how to buy back, how to know when should buy back, etc.)?
```
Because I don't see how the contract handles this **automatically**. 
Looking forward to your reply. :)
Thank you. Have a good coding day.

**Comment by loic001** [comment]
This question really makes sense and I would be very curious to see the answer of the team. Knowing that no oracle is used, I wonder how this is possible?

Of course, a strong assumption is that this situation should not happen, but it is still what is indicated in the documentation! One answer one might expect is that the DAO can do this, except that it is explicitly stated in the document that this is the role of the protocol.

My opinion is that this is pure marketing, what do you think?

**Comment by ind-igo** [comment]
Hey there, thanks for the question. If you see the first Medium post explaining the Olympus system, the intention was always for the price to be close to 1$. The original method for buyback-and-burn was through what was called the Sales contract, which was the precursor to the current Bonds system. This Sales contract was to sell its stablecoin backing in exchange for OHM and then burn the OHM. This way, the protocol is always making a profit.

What happened after launch was that the Sales system evolved into what is now known as Bonds, where OHM is sold in exchange for backing. Since the system never went below backing, there was never any need to make the inverse of this. In the future, we may build something out for this as Inverse Bonds, because in this scheme, the protocol would still make a profit, and it would be a useful mechanism for users to sell OHM without having to dump on an AMM. But this has never been necessary, so it has not been implemented.

Your questions are much appreciated @matthewalan0 @loic001. Hope this gave a little context.
